require './recipe_helper'

include_cookbook 'ufw'
include_cookbook 'essentials'
include_cookbook 'locale'
include_cookbook 'timezone'
include_cookbook 'editor'
include_cookbook 'redis'
include_cookbook 'logentries'
include_cookbook 'nodejs'
include_cookbook 'ruby'
include_cookbook 'kitt'
